all:
  vars:
    ansible_user: root
    ansible_ssh_private_key_file: ~/.ssh/id_rsa
    ansible_ssh_common_args: -o StrictHostKeyChecking=no

k8s-master:
  hosts:
    10.255.205.54:

k8s-worker:
  hosts:
    10.255.205.55:
    10.255.205.56:

monitoring:
  hosts:
    10.255.205.59:
nfs-server:
  hosts:
    10.255.205.57:
nginx:
  hosts:
    10.255.205.58:

puppet-master:
  hosts:
    10.255.205.59:
