- name: Populate k8s nodes mapping
  ansible.builtin.set_fact:
    k8s_nodes: "{{ k8s_nodes | combine({hostvars[item].ansible_hostname: hostvars[item].ansible_default_ipv4.address}) }}"
  loop: "{{ groups['k8s-master'] }}"

- name: Generate env yaml
  delegate_to: localhost
  become: false
  ansible.builtin.template:
    src: environment.yaml.j2
    dest: "{{ playbook_dir }}/production.yaml"
    mode: '755'
